/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package atm;

import static java.lang.Integer.parseInt;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Anuj Bansal
 */
public class singup extends javax.swing.JFrame {

    /**
     * Creates new form singup
     */
    public singup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AccNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Pin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Education = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        PhoneNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DOB = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        Submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Occupation = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setForeground(new java.awt.Color(0, 51, 0));

        jLabel1.setBackground(new java.awt.Color(153, 255, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SINGUP FOM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(522, 522, 522))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 100));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ACCOUNT NUM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 260, 40));

        AccNum.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(AccNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 290, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FIRST NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 220, 40));

        FName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(FName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 290, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LAST NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 220, 40));

        LName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 290, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PIN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 220, 40));

        Pin.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(Pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 290, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Education");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 210, 40));

        Education.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Education.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SCHOLAR", "HIGHER SCHOLAR", "Undergraduate", "POST  GRADUATE", "PASS OUT", " ", " " }));
        getContentPane().add(Education, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 270, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PHONE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 220, 40));

        PhoneNum.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(PhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 290, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATE OF BIRTH");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 240, 40));

        DOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DOB.setMaxSelectableDate(new java.util.Date(1104435116000L));
        DOB.setMinSelectableDate(new java.util.Date(-2177468354000L));
        getContentPane().add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 290, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADDRESS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 210, 40));

        Address.setColumns(20);
        Address.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Address.setRows(5);
        jScrollPane1.setViewportView(Address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 430, 160));

        Submit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 670, 240, 40));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 670, 240, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Occupation");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 210, 40));

        Occupation.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(Occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, 270, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/atm.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;

    private void Clear() {
        AccNum.setText("");
        FName.setText("");
        LName.setText("");
        PhoneNum.setText("");
        Address.setText("");
        Occupation.setText("");
        Pin.setText("");
        Education.setSelectedIndex(-1);

    }

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        String x = Pin.getText();
        String y = AccNum.getText();
        String z = PhoneNum.getText();
        if (AccNum.getText().isEmpty() || FName.getText().isEmpty() || LName.getText().isEmpty() || PhoneNum.getText().isEmpty() || Address.getText().isEmpty() || Occupation.getText().isEmpty() || Pin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");

        } else {
            if (x.length() != 6) {
                JOptionPane.showMessageDialog(this, "Enter Six Digit Pin");
            }
            if (y.length() != 8) {
                JOptionPane.showMessageDialog(this, "Enter Eight Digit Account Number ");
                //acc num update
            }
            if (z.length() != 10) {
                JOptionPane.showMessageDialog(this, "Enter Ten Digit Phone Number ");
                //acc num update
            } else {
                try {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm", "root", "root");
                    PreparedStatement Add = conn.prepareStatement("insert into accsingup values(?,?,?,?,?,?,?,?,?,?)");
                    Add.setInt(1, Integer.valueOf(AccNum.getText()));
                    Add.setString(2, FName.getText());
                    Add.setString(3, LName.getText());
                    Add.setString(4, PhoneNum.getText());
                    Add.setString(5, Address.getText());
                    Add.setString(6, Occupation.getText());
                    Add.setString(7, Education.getSelectedItem().toString());
                    Add.setString(8, DOB.getDate().toString());
                    Add.setInt(9, Integer.valueOf(Pin.getText()));
                    Add.setInt(10, 0);

                    int row = Add.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Account Saved");

                    conn.close();
                    Clear();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Enter Valid Inputs");
                    //JOptionPane.showMessageDialog(this,e);
                }
            }
        }
    }//GEN-LAST:event_SubmitMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Login().setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new singup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNum;
    private javax.swing.JTextArea Address;
    private com.toedter.calendar.JDateChooser DOB;
    private javax.swing.JComboBox<String> Education;
    private javax.swing.JTextField FName;
    private javax.swing.JTextField LName;
    private javax.swing.JTextField Occupation;
    private javax.swing.JTextField PhoneNum;
    private javax.swing.JTextField Pin;
    private javax.swing.JButton Submit;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
